spring:
  application:
    name: producer
  cloud:
    function:
      definition: sendRiderLocation;sendRiderStatus
    stream:
      function:
        definition: sendRiderLocation
      bindings:
        sendRiderLocation-out-0:
          destination: my-topic-new
          content-type: application/json
        sendRiderStatus-out-0:
          destination: my-topic
          content-type: text/plain
      poller:
        fixed-delay: 1000
      kafka:
        binder:
          broker: localhost:9092

#  kafka:
#    producer:
#      bootstrap-servers: localhost:9092
#    cloud:
#      function:
#        definition: uppercase
#      function.web.path: /uppercase
##################
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
#      properties:
#        spring.json.add.type.headers: false
#####################
